version: "3.4"

services:
  backend:
    container_name: backend
    image: backend-cobas
    restart: always
    build:
      context: .
      args:
        GIT_BRANCH: "chogi"
    ports:
    - 8000:8000

  frontend:
    container_name: frontend
    image: frontend-cobas
    restart: always
    build:
      context: frontend
      args:
        GIT_BRANCH: "rohan"
    ports:
    - 3000:3000